### ISSUE TITLE
How to use openni2 with ROS Kinetic ???

### ISSUE THREAD

**Issue by Abduoit** [ros-gbp/openni2_launch#2]
How to use openni2 with Kinetic from the following link 
https://github.com/ros-gbp/openni2_launch#openni2_launch-kinetic---022-0

**Comment by 130s** [comment]
I believe this is a duplicate of https://github.com/ros-drivers/openni2_camera/issues/84. Closing as I already responded in https://github.com/ros-drivers/openni2_camera/issues/84#issuecomment-401837928. Also please go through [ROS support guideline](http://wiki.ros.org/Support) -- duplicating questions is not encouraged.
